export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malaysia",
  "Malta",
  "Mexico",
  "Moldova",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
];

export const LANGUAGES = [
  "English",
  "Mandarin Chinese",
  "Hindi",
  "Spanish",
  "French",
  "Arabic",
  "Bengali",
  "Japanese",
  "Portuguese",
  "Russian",
  "German",
  "Vietnamese",
  "Italian",
  "Urdu"
];

export const FIELDS_OF_STUDY = [
  "Computer Science",
  "Computer Engineering",
  "Software Engineering",
  "Data Science",
  "Psychology",
  "Design / HCI",
  "Business / Finance",
  "Biology / Bioinformatics",
  "Law / Policy",
  "Education / Social Sciences",
  "Other",
];

export const CURRENT_STATUSES = [
  "High school student",
  "University student",
  "Working + studying",
  "Only working",
  "Other",
];

export const JOB_ROLES = [
  "Software engineer",
  "Data scientist",
  "Data analyst",
  "Product manager",
  "UX/UI designer",
  "Graphic designer",
  "Teacher",
  "Nurse",
  "Doctor",
  "Marketing specialist",
  "Salesperson",
  "Customer support",
  "Consulting",
  "Other",
];

export const FINANCIAL_SUPPORT_RETURN_OPTIONS = [
  "Philanthropy",
  "Income_Share",
  "Work_Back_Service",
  "Unspecified",
];
